
import React from 'react';
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Check, Globe, Info, Loader2, RefreshCw } from 'lucide-react';

interface QRCodeTabProps {
  newAccountName: string;
  setNewAccountName: (name: string) => void;
  qrCodeUrl: string;
  showQrLoader: boolean;
  handleRefreshQrCode: () => void;
  openWebWhatsApp: () => void;
  loading: boolean;
  onAddAccount: () => void;
}

const QRCodeTab = ({
  newAccountName,
  setNewAccountName,
  qrCodeUrl,
  showQrLoader,
  handleRefreshQrCode,
  openWebWhatsApp,
  loading,
  onAddAccount
}: QRCodeTabProps) => {
  return (
    <div className="space-y-4 py-4">
      <div className="space-y-2">
        <Label htmlFor="qr-name">Device Name</Label>
        <Input
          id="qr-name"
          placeholder="e.g., Marketing Account"
          value={newAccountName}
          onChange={(e) => setNewAccountName(e.target.value)}
        />
      </div>
      
      <Alert className="mb-4">
        <Info className="h-4 w-4" />
        <AlertDescription>
          In a real implementation, this QR code would be generated by the WhatsApp Business API.
          Scan it with your WhatsApp app to connect.
        </AlertDescription>
      </Alert>
      
      <div className="border rounded-md p-6 flex flex-col items-center justify-center">
        {showQrLoader ? (
          <div className="flex flex-col items-center justify-center h-32 w-32">
            <Loader2 className="h-8 w-8 text-primary animate-spin" />
            <p className="text-sm text-muted-foreground mt-4">Generating QR code...</p>
          </div>
        ) : (
          <img src={qrCodeUrl} alt="WhatsApp QR Code" className="h-32 w-32" />
        )}
        <p className="text-sm text-muted-foreground mt-4 text-center">
          Scan this QR code with your WhatsApp app to connect
        </p>
        <div className="flex gap-2 mt-4">
          <Button variant="outline" size="sm" onClick={handleRefreshQrCode}>
            <RefreshCw className="mr-2 h-3 w-3" />
            Refresh QR Code
          </Button>
          <Button variant="outline" size="sm" onClick={openWebWhatsApp}>
            <Globe className="mr-2 h-3 w-3" />
            Open in Browser
          </Button>
        </div>
      </div>
      
      <Button 
        className="w-full" 
        onClick={onAddAccount}
        disabled={loading || !newAccountName}
      >
        {loading ? (
          <>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Connecting...
          </>
        ) : (
          <>
            <Check className="mr-2 h-4 w-4" />
            Confirm Connection
          </>
        )}
      </Button>
    </div>
  );
};

export default QRCodeTab;
